# Generated by Django 5.2.8 on 2025-11-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nome do cliente / Nome fantasia')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão social')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('is_client', models.BooleanField(default=True, verbose_name='Cliente')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Fornecedor')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Parceiro')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Funcionário')),
                ('is_other', models.BooleanField(default=False, verbose_name='Outros')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['display_name'],
            },
        ),
    ]
