# Generated by Django 5.2.8 on 2025-11-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_email_contact_is_active_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_contacts', models.BooleanField(default=True, verbose_name='Pode gerenciar contatos')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Pode gerenciar usuários')),
                ('user_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.usercompany', verbose_name='Usuário da empresa')),
            ],
            options={
                'verbose_name': 'Permissão do usuário',
                'verbose_name_plural': 'Permissões dos usuários',
            },
        ),
    ]
