# Generated by Django 5.2.8 on 2025-11-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompany',
            options={'ordering': ['company', 'user__username'], 'verbose_name': 'Usuário da empresa', 'verbose_name_plural': 'Usuários da empresa'},
        ),
        migrations.AddField(
            model_name='usercompany',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Usuário principal, não pode perder acesso.', verbose_name='Dono da empresa'),
        ),
    ]
