# Generated by Django 5.2.8 on 2025-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='can_manage_products',
            field=models.BooleanField(default=False, verbose_name='Pode gerenciar produtos'),
        ),
    ]
