# Generated by Django 5.2.8 on 2025-11-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userpermission_can_manage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Vendedor'),
        ),
    ]
