# Generated by Django 5.2.8 on 2025-11-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userpermission_can_manage_sectors_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Informe a comissão em porcentagem, ex.: 5,00 para 5%.', max_digits=5, null=True, verbose_name='Comissão (%)'),
        ),
    ]
