# Generated by Django 5.2.8 on 2025-11-20 18:43

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_cost_price_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.company_logo_upload_path, verbose_name='Logo da empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_default_message',
            field=models.TextField(blank=True, help_text='Mensagem sugerida ao iniciar uma conversa pelo WhatsApp.', null=True, verbose_name='Mensagem padrão do WhatsApp'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro')], default='dark', max_length=10, verbose_name='Tema')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência do usuário',
                'verbose_name_plural': 'Preferências dos usuários',
            },
        ),
    ]
